[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.install]
cmds = [
  "mkdir -p src/main/java/com/agrocloud",
  "cp agrogestion-backend/pom-http.xml pom.xml",
  "cp agrogestion-backend/src/main/java/com/agrocloud/HttpServer.java src/main/java/com/agrocloud/"
]

[phases.build]
cmds = [
  "mvn --version",
  "ls -la",
  "mvn clean package -DskipTests -X"
]

[start]
cmd = "java -jar target/agrocloud-http-1.0.0.jar"
