[phases.setup]
nixPkgs = ["openjdk17"]

[phases.install]
cmds = [
  "mkdir -p target/classes",
  "mkdir -p META-INF"
]

[phases.build]
cmds = [
  "java -version",
  "javac -d target/classes agrogestion-backend/src/main/java/com/agrocloud/HttpServer.java",
  "cd target/classes && jar cfm ../agrocloud-http.jar ../../META-INF/MANIFEST.MF com/agrocloud/*.class && cd ../.."
]

[start]
cmd = "java -jar target/agrocloud-http.jar"
