name: Maven Tests - AgroGestion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: agrocloud_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -p123456"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Wait for MySQL
      run: |
        echo "Esperando a que MySQL esté listo..."
        for i in {1..30}; do
          if mysqladmin ping -h"127.0.0.1" -P3306 -u"root" -p"123456" --silent; then
            echo "MySQL está listo!"
            break
          fi
          echo "Intento $i/30: MySQL no está listo, esperando..."
          sleep 2
        done
        
    - name: Verify MySQL connection
      run: |
        echo "Verificando conexión a MySQL..."
        mysql -h 127.0.0.1 -P 3306 -u root -p"123456" -e "SHOW DATABASES;"
        
    - name: Create test database
      run: |
        echo "Creando base de datos de pruebas..."
        mysql -h 127.0.0.1 -P 3306 -u root -p"123456" -e "CREATE DATABASE IF NOT EXISTS agrocloud_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
        
    - name: Run tests
      run: mvn test -Dspring.profiles.active=test
      working-directory: ./agrogestion-backend
      env:
        DB_USER: root
        DB_PASS: 123456
        
    - name: Generate test reports
      run: mvn jacoco:report
      working-directory: ./agrogestion-backend
      if: always()
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          agrogestion-backend/target/surefire-reports/
          agrogestion-backend/target/site/jacoco/
        retention-days: 30